openapi: 3.0.0
info:
  title: Movie Review API
  description: API for managing movie reviews.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /reviews:
    get:
      summary: Get all movie reviews
      responses:
        '200':
          description: List of reviews
    post:
      summary: Add a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - movie_title
                - reviewer
                - rating
                - review
              properties:
                movie_title:
                  type: string
                reviewer:
                  type: string
                rating:
                  type: integer
                review:
                  type: string
      responses:
        '201':
          description: Review added successfully

  /reviews/{id}:
    get:
      summary: Get a review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Review found
        '404':
          description: Review not found
    put:
      summary: Update a review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_title:
                  type: string
                reviewer:
                  type: string
                rating:
                  type: integer
                review:
                  type: string
      responses:
        '200':
          description: Review updated
        '404':
          description: Review not found
    delete:
      summary: Delete a review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Review deleted
        '404':
          description: Review not found
